# Event Names Constant

# STT Events
STT_REQUEST = "STT_REQUEST"
STT_RESPONSE = "STT_RESPONSE"
STT_ERROR = "STT_ERROR"

# Processing / LLM Events
PROCESSING = "PROCESSING"

# TTS Events
TTS_REQUEST = "TTS_REQUEST"
TTS_RESPONSE = "TTS_RESPONSE"
TTS_ERROR = "TTS_ERROR"
